version: '3'

services:
  web:
    restart: always
    env_file: .env
    build: .
    ports:
      - "8000:8000"
    links:
      - postgres:postgres
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: postgres
    command: "python manage.py runserver 0:8000"
    depends_on:
      - postgres

  postgres:
    env_file: .env
    restart: always
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
